const skillList = [
    {label: "Adobe", value: "A1"},
    {label: "Adobe Animate", value: "A2"},
    {label: "Adobe Fireworks", value: "A3"},
    {label: "Adobe XD", value: "A4"},
    {label: "Adobe Premiere", value: "A5"},
    {label: "Adobe Indesign", value: "A6"},
    {label: "Adobe Photoshop", value: "A7"},
    {label: "Adobe illustrator", value: "A8"},
    {label: "Adobe After Effect", value: "A9"},
    {label: "Adobe Dreamweaver", value: "A10"},
    {label: "Adobe Lightroom", value: "A11"},
    {label: "Auto CAD", value: "Au1"},
    {label: "Axure", value: "Au2"},
    {label: "Balsamiq", value: "B1"},
    {label: "Blender", value: "B2"},
    {label: "Cinema4D", value: "C1"},
    {label: "Figma", value: "F1"},
    {label: "Framer", value: "F2"},
    {label: "Invision", value: "I1"},
    {label: "Marvel App", value: "M1"},
    {label: "Miro", value: "M2"},
    {label: "Proto.io", value: "P1"},
    {label: "Rhino", value: "R1"},
    {label: "Sketch", value: "S1"},
    {label: "Sketch Up", value: "S2"},
    {label: "Protopie", value: "P2"},
    {label: "Whimsical Wireframes", value: "W1"},
    {label: "Zepline", value: "Z1"},
    {label: "3D Max", value: "D1"},
    
]

export default skillList;