const skillList = [
  { label: "Adobe", value: "Adobe" },
  { label: "Adobe Animate", value: "Adobe Animate" },
  { label: "Adobe Fireworks", value: "Adobe Fireworks" },
  { label: "Adobe XD", value: "Adobe XD" },
  { label: "Adobe Premiere", value: "Adobe Premiere" },
  { label: "Adobe Indesign", value: "Adobe Indesign" },
  { label: "Adobe Photoshop", value: "Adobe Photoshop" },
  { label: "Adobe illustrator", value: "Adobe Illustrator" },
  { label: "Adobe After Effect", value: "Adobe After Effect" },
  { label: "Adobe Dreamweaver", value: "Adobe Dreamweaver" },
  { label: "Adobe Lightroom", value: "Adobe Lightroom" },
  { label: "Auto CAD", value: "Auto CAD" },
  { label: "Axure", value: "Axure" },
  { label: "Balsamiq", value: "Balsamiq" },
  { label: "Blender", value: "Blender" },
  { label: "Cinema4D", value: "Cinema4D" },
  { label: "Figma", value: "Figma" },
  { label: "Framer", value: "Framer" },
  { label: "Invision", value: "Invision" },
  { label: "Marvel App", value: "Marvel App" },
  { label: "Miro", value: "Miro" },
  { label: "Proto.io", value: "Proto.io" },
  { label: "Rhino", value: "Rhino" },
  { label: "Sketch", value: "Sketch" },
  { label: "Sketch Up", value: "Sketch Up" },
  { label: "Protopie", value: "Protopie" },
  { label: "Whimsical Wireframes", value: "Whimsical Wireframes" },
  { label: "Zepline", value: "Zepline" },
  { label: "3D Max", value: "3D Max" },
];

export default skillList;
